//! What a file extension is called, and what shelf it sits on.
//!
//! **Generated. Do not edit by hand** — run `node scripts/formats.mjs`, which
//! reads the original's own generated catalogue and writes this. See that
//! script for where the table comes from and why it is committed rather than
//! built.
//!
//! 1367 extensions named, across 1359 filed into 102 families in
//! 12 categories.
//!
//! ## This names, it does not classify
//!
//! Nothing in here decides what *kind of card* a file becomes. That is
//! `import::by_extension`'s job and it stays a short hand-written table on
//! purpose: this catalogue knows a `.cr3` is a photograph, and calling it an
//! image card would put a frame on the board that can never draw, because
//! nothing in this tree decodes Canon RAW. A name is safe to be generous with;
//! a card type is not.
//!
//! So what this is for is the *word* on a card and in the information rail. A
//! `.sldprt` reading "SolidWorks part" rather than "file" is the whole of the
//! feature, and it costs a binary search.

/// The twelve shelves everything is filed on.
///
/// Coarser than a family and useful where a family is too specific to show —
/// a card that says "Images" is a card somebody can sort by.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Category {
    Images,
    Audio,
    Video,
    Design,
    Documents,
    Data,
    ThreeD,
    Archives,
    Maps,
    Games,
    Security,
    System,
}

impl Category {
    /// What the shelf is called, spelled the way the original spells it.
    pub fn label(self) -> &'static str {
        match self {
            Self::Images => "Images",
            Self::Audio => "Audio",
            Self::Video => "Video",
            Self::Design => "Design",
            Self::Documents => "Documents & e-books",
            Self::Data => "Data & code",
            Self::ThreeD => "3D / CAD / engineering",
            Self::Archives => "Archives",
            Self::Maps => "Maps & GIS",
            Self::Games => "Games",
            Self::Security => "Email & security",
            Self::System => "System & disk",
        }
    }
}

/// A family of formats — a shelf's worth, with the shelf named.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Family {
    pub label: &'static str,
    pub category: Category,
}

/// What this format is called: "Hasselblad RAW", "7-Zip archive".
///
/// `None` for an extension the catalogue has never heard of, which is a real
/// answer — the caller has its own word for that and it is not this module's
/// to invent.
pub fn name(ext: &str) -> Option<&'static str> {
    lookup(&NAMES, ext).copied()
}

/// Which family this format belongs to, where it belongs to one.
///
/// Broader than [`name`] and answered for fewer extensions: a handful of
/// formats are named outright without any family claiming them.
pub fn family(ext: &str) -> Option<Family> {
    lookup(&SHELVES, ext).map(|&i| FAMILIES[i as usize])
}

/// A binary search over a table sorted at generation time.
///
/// Sorted here rather than at startup, which is what lets both tables be
/// `static` and cost nothing until something is dropped on the board. The
/// order is byte order over ASCII, which is what
/// `the_tables_are_sorted_the_way_the_search_expects` holds.
fn lookup<'t, T>(table: &'t [(&'static str, T)], ext: &str) -> Option<&'t T> {
    // The catalogue is lowercase with no leading dot, and a name off a disk is
    // neither reliably. Borrowed where it already matches, so the ordinary
    // case allocates nothing.
    let key = ext.trim_start_matches('.');
    let owned;
    let key = if key.bytes().any(|b| b.is_ascii_uppercase()) {
        owned = key.to_ascii_lowercase();
        owned.as_str()
    } else {
        key
    };
    let at = table.binary_search_by_key(&key, |(k, _)| *k).ok()?;
    Some(&table[at].1)
}

/// Every family, addressed by index from [`SHELVES`].
static FAMILIES: [Family; 102] = [
    Family { label: "Photo", category: Category::Images },
    Family { label: "RAW photo", category: Category::Images },
    Family { label: "XMP sidecar", category: Category::Images },
    Family { label: "RAW sidecars / cinema", category: Category::Images },
    Family { label: "Images (more)", category: Category::Images },
    Family { label: "Sound", category: Category::Audio },
    Family { label: "Lyrics", category: Category::Audio },
    Family { label: "MIDI", category: Category::Audio },
    Family { label: "Music production", category: Category::Audio },
    Family { label: "Surround audio", category: Category::Audio },
    Family { label: "Audio (more)", category: Category::Audio },
    Family { label: "Video", category: Category::Video },
    Family { label: "Colour LUT", category: Category::Video },
    Family { label: "Editing timeline", category: Category::Video },
    Family { label: "After Effects", category: Category::Video },
    Family { label: "Gyro log", category: Category::Video },
    Family { label: "Premiere Pro", category: Category::Video },
    Family { label: "DaVinci Resolve", category: Category::Video },
    Family { label: "VEGAS Pro", category: Category::Video },
    Family { label: "Subtitles", category: Category::Video },
    Family { label: "Video editing", category: Category::Video },
    Family { label: "Video / streaming (more)", category: Category::Video },
    Family { label: "Illustrator", category: Category::Design },
    Family { label: "Photoshop", category: Category::Design },
    Family { label: "Raster art", category: Category::Design },
    Family { label: "Vector graphics", category: Category::Design },
    Family { label: "Adobe", category: Category::Design },
    Family { label: "Design", category: Category::Design },
    Family { label: "PDF", category: Category::Documents },
    Family { label: "DjVu", category: Category::Documents },
    Family { label: "Kindle e-book", category: Category::Documents },
    Family { label: "Office docs", category: Category::Documents },
    Family { label: "Text & markup", category: Category::Documents },
    Family { label: "Apple iWork", category: Category::Documents },
    Family { label: "Fonts", category: Category::Documents },
    Family { label: "Text art", category: Category::Documents },
    Family { label: "Documents / e-books (more)", category: Category::Documents },
    Family { label: "Documents / publishing (more)", category: Category::Documents },
    Family { label: "Fonts (more)", category: Category::Documents },
    Family { label: "Visual Studio solution", category: Category::Data },
    Family { label: "Notebooks & data", category: Category::Data },
    Family { label: "Access database", category: Category::Data },
    Family { label: "Data", category: Category::Data },
    Family { label: "Web / code", category: Category::Data },
    Family { label: "Git objects", category: Category::Data },
    Family { label: "Databases", category: Category::Data },
    Family { label: "Config", category: Category::Data },
    Family { label: "Electronics, runtime & backups (more)", category: Category::Data },
    Family { label: "Logs", category: Category::Data },
    Family { label: "Developer / data", category: Category::Data },
    Family { label: "Source code & build files", category: Category::Data },
    Family { label: "Developer / data (more)", category: Category::Data },
    Family { label: "Native code, ML & misc (more)", category: Category::Data },
    Family { label: "3D model", category: Category::ThreeD },
    Family { label: "Fusion 360", category: Category::ThreeD },
    Family { label: "SolidWorks", category: Category::ThreeD },
    Family { label: "G-code", category: Category::ThreeD },
    Family { label: "Diagrams", category: Category::ThreeD },
    Family { label: "Altium (EDA)", category: Category::ThreeD },
    Family { label: "KiCad (EDA)", category: Category::ThreeD },
    Family { label: "IPC netlist (EDA)", category: Category::ThreeD },
    Family { label: "CAD", category: Category::ThreeD },
    Family { label: "CAD exchange", category: Category::ThreeD },
    Family { label: "3D / printing", category: Category::ThreeD },
    Family { label: "Engineering", category: Category::ThreeD },
    Family { label: "Science / medical / engineering", category: Category::ThreeD },
    Family { label: "3D / CAD / point clouds (more)", category: Category::ThreeD },
    Family { label: "3D / CAD (more)", category: Category::ThreeD },
    Family { label: "Science / engineering (more)", category: Category::ThreeD },
    Family { label: "Archives", category: Category::Archives },
    Family { label: "Archives (packages)", category: Category::Archives },
    Family { label: "Archives (more)", category: Category::Archives },
    Family { label: "Map data", category: Category::Maps },
    Family { label: "GIS / mapping", category: Category::Maps },
    Family { label: "Geospatial / GIS", category: Category::Maps },
    Family { label: "GIS / mapping (more)", category: Category::Maps },
    Family { label: "Unity", category: Category::Games },
    Family { label: "Game engines", category: Category::Games },
    Family { label: "Game saves", category: Category::Games },
    Family { label: "Valve / Steam", category: Category::Games },
    Family { label: "Game ROMs / assets", category: Category::Games },
    Family { label: "Game assets (more)", category: Category::Games },
    Family { label: "REDengine (Cyberpunk 2077)", category: Category::Games },
    Family { label: "Marathon (Aleph One)", category: Category::Games },
    Family { label: "Unity / IL2CPP", category: Category::Games },
    Family { label: "Source 2 (Valve)", category: Category::Games },
    Family { label: "Email", category: Category::Security },
    Family { label: "Certificates", category: Category::Security },
    Family { label: "Calendar / contacts", category: Category::Security },
    Family { label: "Security / keys / certs", category: Category::Security },
    Family { label: "Email / contacts (more)", category: Category::Security },
    Family { label: "Security / forensics (more)", category: Category::Security },
    Family { label: "Disk images", category: Category::System },
    Family { label: "Recordings", category: Category::System },
    Family { label: "Executables", category: Category::System },
    Family { label: "Camera catalog", category: Category::System },
    Family { label: "Shortcuts", category: Category::System },
    Family { label: "Other", category: Category::System },
    Family { label: "Niche / rare formats", category: Category::System },
    Family { label: "Disk images / firmware", category: Category::System },
    Family { label: "System / misc", category: Category::System },
    Family { label: "Disk images / firmware (more)", category: Category::System },
];

/// Extension to what the format is called. Sorted; see [`lookup`].
#[rustfmt::skip]
static NAMES: [(&str, &str); 1367] = [
    ("1", "Unix manual page (troff)"), ("1pux", "1Password export"), ("264", "H.264 stream"),
    ("265", "H.265 stream"), ("3dm", "Rhino 3D model"), ("3ds", "3D Studio model"),
    ("3dsx", "3DS homebrew"), ("3dxml", "Dassault 3DXML"), ("3fr", "Hasselblad RAW"),
    ("3g2", "3G2 mobile video"), ("3ga", "3GPP audio"), ("3gp", "3GP mobile video"),
    ("3mf", "3MF 3D print"), ("669", "Composer 669 module"), ("7z", "7-Zip archive"),
    ("a", "Static library (ar)"), ("a26", "Atari 2600 ROM"), ("a78", "Atari 7800 ROM"),
    ("aac", "AAC audio"), ("aae", "Apple Photos edit"), ("ab", "Android backup"),
    ("ab1", "DNA sequencing trace"), ("abbu", "Apple Contacts backup"),
    ("abc", "Alembic cache"), ("abf", "Axon electrophysiology"), ("abr", "Photoshop brushes"),
    ("abw", "AbiWord document"), ("ac", "Autoconf Script"), ("ac3", "Dolby Digital (AC-3)"),
    ("accdb", "Access database"), ("ace", "ACE archive"), ("acf", "Steam app manifest"),
    ("aco", "Photoshop swatches"), ("acv", "Photoshop Curves preset"),
    ("addcont_keystone", "REDengine add-on content keystone"),
    ("addrcatalog", "Unity Addressables catalog"), ("adf", "ADF file"),
    ("adi", "Active@ Disk Image Backup"), ("adoc", "AsciiDoc"),
    ("aep", "After Effects project"), ("aepx", "After Effects project (XML)"),
    ("aet", "After Effects template"), ("afdesign", "Affinity Designer document"),
    ("aff", "Forensic disk image"), ("aff4", "Forensic image (AFF4)"), ("afl", "Adobe Flash"),
    ("afphoto", "Affinity Photo document"), ("afpub", "Affinity Publisher document"),
    ("agc", "Google Camera config"), ("ai", "Adobe Illustrator artwork"),
    ("aiff", "AIFF audio"), ("alp", "Ableton Live Pack"), ("als", "Ableton Live set"),
    ("am", "Automake File"), ("amf", "AMF 3D print"), ("amr", "AMR audio"),
    ("ani", "Animated cursor"), ("anim", "Unity animation clip"), ("ape", "Monkey’s Audio"),
    ("apk", "Android app"), ("apkg", "Anki deck"), ("apkm", "APKMirror App Bundle"),
    ("apks", "Android App Set"), ("appimage", "Linux AppImage"),
    ("appl", "Marathon / Aleph One plugin data"), ("appx", "Windows app package"),
    ("arc", "ARC archive"), ("archive", "REDengine 4 archive (Cyberpunk 2077)"),
    ("ari", "ARRIRAW frame"), ("arj", "ARJ archive"), ("arrow", "Apache Arrow"),
    ("arw", "Sony RAW"), ("arx", "ARRIRAW"), ("asar", "Electron archive"),
    ("asc", "Esri ASCII grid"), ("asciidoc", "AsciiDoc document"), ("ase", "Aseprite sprite"),
    ("aseprite", "Aseprite sprite"), ("asf", "Advanced Systems Format"),
    ("asl", "Photoshop layer styles"), ("asm", "CAD assembly file"),
    ("asp", "Classic ASP page"), ("aspx", "ASP.NET Web Page"), ("ass", "ASS subtitles"),
    ("asset", "Unity asset"), ("assets", "Unity assets"), ("asx", "Windows Media playlist"),
    ("atlas", "Texture atlas"), ("atmos", "Dolby Atmos"), ("atom", "Atom feed"),
    ("au", "Sun audio"), ("aup", "Audacity project (legacy)"), ("aup3", "Audacity project"),
    ("authorized_keys", "OpenSSH authorized_keys"), ("avc", "H.264 / AVC stream"),
    ("avi", "AVI video"), ("avif", "AVIF image"), ("awb", "AMR Wideband"),
    ("awt", "AbiWord template"), ("axf", "ARM executable"), ("ay", "AY chiptune"),
    ("azw", "Kindle e-book (AZW)"), ("azw3", "Kindle e-book (AZW3)"), ("bak", "Backup File"),
    ("bam", "Binary alignment map"), ("band", "GarageBand project"),
    ("bank", "Game sound bank"), ("bash", "Bash Script"), ("basis", "Basis Universal texture"),
    ("bat", "Batch script"), ("bay", "Casio raw photo"), ("bcf", "Binary variant call"),
    ("bdf", "BioSemi Data Format"), ("bepis", "ULTRAKILL save"), ("bib", "BibTeX bibliography"),
    ("bie", "JBIG codestream"), ("bil", "ENVI band-interleaved raster"),
    ("binwalk", "Firmware dump"), ("bip", "ENVI band-interleaved raster"),
    ("bk", "Backup Container"), ("bk2", "Bink Video 2"), ("blend", "Blender file"),
    ("bmp", "Bitmap image"), ("bnk", "Wwise sound bank"), ("book", "FrameMaker book"),
    ("bps", "BPS ROM patch"), ("br", "Brotli stream"), ("braw", "Blackmagic RAW"),
    ("brd", "PCB layout (EAGLE)"), ("brep", "BREP CAD solid"),
    ("browser", "ASP.NET Browser Definition"), ("bson", "Binary JSON"),
    ("bsp", "Compiled game map"), ("bsq", "ENVI band-sequential raster"),
    ("build", "Meson build definition"), ("bundle", "Unity AssetBundle"),
    ("bw", "SGI greyscale image"), ("bw64", "Broadcast Wave 64-bit"), ("bwf", "Broadcast Wave"),
    ("bz2", "BZip2 archive"), ("c", "C Source"), ("c4d", "Cinema 4D scene"),
    ("cab", "Windows Cabinet"), ("caf", "Core Audio Format"), ("cap", "Network capture"),
    ("capnp", "Cap’n Proto schema"), ("capnproto", "Cap’n Proto schema"),
    ("catpart", "CATIA part"), ("catproduct", "CATIA assembly"), ("cb7", "Comic Book 7z"),
    ("cba", "Comic Book ACE"), ("cbor", "CBOR data"), ("cbr", "Comic Book RAR"),
    ("cbt", "Comic Book TAR"), ("cbz", "Comic Book ZIP"), ("cc", "C++ Source"),
    ("ccd", "CloneCD image"), ("cdb", "ANSYS model database"), ("cdf", "NetCDF data"),
    ("cdi", "DiscJuggler image"), ("cdp", "CDP model file"), ("cdr", "CorelDRAW drawing"),
    ("cdx", "ChemDraw drawing"), ("cdxml", "ChemDraw XML"), ("cer", "X.509 certificate"),
    ("cfg", "Config file"), ("cgm", "Computer Graphics Metafile"),
    ("cgp", "Pattern / grid data (.cgp)"), ("cgr", "CATIA Graphics"),
    ("chd", "MAME disc image"), ("chm", "Compiled HTML Help"),
    ("chroma", "Razer Chroma animation"), ("cia", "3DS install package"),
    ("cif", "Crystallographic Information File"), ("cin", "Kodak Cineon"),
    ("cine", "Phantom high-speed video"), ("cir", "SPICE circuit"),
    ("citationcff", "Citation File Format (CITATION.cff)"), ("cl3", "Topcon scan (CL3)"),
    ("clang-format", "Clang-Format Config"), ("clang-tidy", "Clang-Tidy Config"),
    ("class", "Java class file"), ("clr", "Topcon scan (CLR)"), ("cls", "LaTeX class"),
    ("cmake", "CMake Script"), ("cmd", "Windows command script"), ("cnc", "CNC program"),
    ("cnf", "Configuration file"), ("cnt", "Neuroscan EEG"), ("cof", "Capture One settings"),
    ("comask", "Capture One mask"), ("comp", "GLSL Compute Shader"), ("conda", "Conda package"),
    ("conf", "Config file"), ("config", "Configuration File"), ("contact", "Windows contact"),
    ("controller", "Unity Animator Controller"), ("cop", "Capture One settings"),
    ("copying", "Licence text (COPYING)"), ("cos", "Capture One settings"),
    ("cpg", "Code page file"), ("cpio", "cpio archive"), ("cpp", "C++ Source"),
    ("cpr", "Cubase project"), ("cpt", "Colour palette (CPT)"), ("cr2", "Canon RAW (CR2)"),
    ("cr3", "Canon RAW (CR3)"), ("cramfs", "cramfs image"), ("crash", "Crash report"),
    ("crdownload", "Chrome partial download"), ("crl", "Certificate revocation list"),
    ("crm", "Canon Cinema RAW Light"), ("crt", "X.509 certificate"), ("crw", "Canon RAW (CRW)"),
    ("crx", "Chrome extension"), ("cs", "C# Source"), ("cso", "Compressed ISO"),
    ("csproj", "C# project"), ("csr", "Certificate request"), ("css", "CSS stylesheet"),
    ("csv", "CSV table"), ("ctg", "Canon camera catalog"), ("cube", "Gaussian cube"),
    ("cubemap", "Unity cubemap"), ("cue", "Cue sheet"), ("cur", "Windows cursor"),
    ("cursorignore", "Cursor Ignore Rules"), ("cxx", "C++ Source"), ("dae", "COLLADA scene"),
    ("dart", "Dart Source"), ("dav", "Dahua CCTV video"), ("db", "Database file"),
    ("db-shm", "SQLite shared-memory index (.db sidecar)"),
    ("db-wal", "SQLite write-ahead log (.db sidecar)"), ("db3", "SQLite database"),
    ("db3-shm", "SQLite shared-memory index (.db3 sidecar)"),
    ("db3-wal", "SQLite write-ahead log (.db3 sidecar)"), ("dbf", "dBASE table"),
    ("dbx", "Outlook Express folder"), ("dcm", "DICOM medical image"),
    ("dcr", "Kodak RAW (DCR)"), ("dcs", "Kodak RAW (DCS)"), ("dds", "DirectDraw Surface"),
    ("deb", "Debian package"), ("def", "Module Definition File"), ("der", "DER certificate"),
    ("desc", "Protobuf descriptor set"), ("desktop", "Linux desktop entry"),
    ("dff", "DSD audio (DFF)"), ("dfu", "USB DFU image"), ("dicom", "DICOM medical image"),
    ("dif", "DV stream"), ("diff", "Diff file"), ("dio", "draw.io diagram"),
    ("dita", "DITA topic"), ("ditamap", "DITA map"), ("divx", "DivX video"),
    ("djifw", "DJI Firmware"), ("djv", "DjVu document"), ("djvu", "DjVu document"),
    ("dll", "Windows library"), ("dls", "Downloadable Sounds"), ("dlv", "CATIA V4 file"),
    ("dmg", "macOS disk image"), ("dmp", "Crash / memory dump"), ("dng", "Digital Negative"),
    ("doc", "Word 97-2003 document"), ("dockerignore", "Docker Ignore Rules"),
    ("docm", "Word macro-enabled document"), ("docx", "Word document"),
    ("dop", "DxO PhotoLab sidecar"), ("dot", "Word 97 template"),
    ("dotm", "Word macro-enabled template"), ("dotx", "Word template"),
    ("dox", "Doxygen Config"), ("doxygen", "Doxygen Config"),
    ("dpx", "Digital Picture Exchange"), ("drawio", "diagrams.net diagram"),
    ("drc", "Draco mesh"), ("drl", "Excellon drill file"), ("drp", "DaVinci Resolve project"),
    ("drt", "DaVinci Resolve timeline"), ("ds_store", "macOS folder metadata"),
    ("dsd", "DraStic shader"), ("dsf", "DSD audio (DSF)"), ("dsi", "Nintendo DSi ROM"),
    ("dsk", "Floppy disk image"), ("dsm", "DeSmuME movie"), ("dsv", "DeSmuME save"),
    ("dsym", "Apple debug symbols"), ("dt0", "DTED level 0"), ("dt1", "DTED level 1"),
    ("dt2", "DTED level 2"), ("dta", "Stata dataset"), ("dtb", "Device Tree Blob"),
    ("dtbo", "Device Tree Overlay"), ("dted", "DTED elevation"), ("dts", "DTS audio"),
    ("dump", "Data dump"), ("dv", "Digital Video"), ("dvi", "TeX DVI"),
    ("dvr-ms", "Media Center recording"), ("dwarf", "DWARF debug info"),
    ("dwg", "AutoCAD drawing"), ("dwt", "AutoCAD template"), ("dx", "JCAMP-DX spectrum"),
    ("dxf", "CAD drawing exchange (DXF)"), ("dylib", "macOS dynamic library"),
    ("e01", "EnCase forensic image"), ("e57", "E57 point cloud"),
    ("eac3", "Dolby Digital Plus"), ("ear", "Enterprise Archive"),
    ("ec3", "Dolby Digital Plus"), ("ecw", "ECW image"), ("edb", "Exchange database"),
    ("edf", "European Data Format"), ("editorconfig", "EditorConfig"),
    ("edl", "Edit Decision List"), ("eeg", "EEG recording"), ("eip", "Capture One package"),
    ("elf", "ELF executable"), ("emf", "Enhanced Metafile"), ("eml", "Email message"),
    ("emlx", "Apple Mail message"), ("emz", "Compressed Enhanced Metafile"),
    ("enc", "Encrypted File"), ("entitlements", "Apple entitlements"),
    ("env", "Environment file"), ("eot", "Embedded OpenType Font"),
    ("eps", "Encapsulated PostScript"), ("epsf", "Encapsulated PostScript"),
    ("epsi", "EPS Interchange"), ("epub", "EPUB e-book"), ("epw", "SamacSys ECAD model"),
    ("erf", "Epson RAW"), ("esd", "Windows ESD image"), ("eslintignore", "ESLint Ignore Rules"),
    ("eslintrc", "ESLint Config"), ("etl", "Event Trace Log"),
    ("evt", "Windows Event Log (legacy)"), ("evtx", "Windows Event Log"),
    ("ewf", "EnCase forensic image"), ("exe", "Windows program"), ("exp", "CATIA export"),
    ("exr", "OpenEXR image"), ("ext", "ext filesystem image"),
    ("ext4", "ext4 filesystem image"), ("f", "Fortran source (fixed-form)"),
    ("f3d", "Fusion 360 design"), ("f3z", "Fusion 360 archive"),
    ("f4m", "Flash Media Manifest"), ("f4v", "Flash MP4 video"), ("f90", "Fortran 90 source"),
    ("f95", "Fortran 95 source"), ("fa", "FASTA sequence"), ("faa", "FASTA proteins"),
    ("far", "Farandole module"), ("farbfeld", "farbfeld image"), ("fasta", "FASTA sequence"),
    ("fastq", "FASTQ reads"), ("fb2", "FictionBook e-book"), ("fb3", "FictionBook 3"),
    ("fbs", "FlatBuffers schema"), ("fbx", "FBX 3D scene"), ("fcpxml", "Final Cut Pro XML"),
    ("fd", "UEFI/BIOS flash"), ("feather", "Arrow Feather"), ("ff", "farbfeld image"),
    ("fff", "Hasselblad RAW (FFF)"), ("fig", "Figma design"),
    ("fila", "Marathon / Aleph One film"), ("fish", "Fish Script"), ("fit", "Garmin activity"),
    ("fits", "Astronomy image (FITS)"), ("fla", "Animate (Flash) source"),
    ("flac", "FLAC audio"), ("flatpak", "Flatpak bundle"), ("flif", "FLIF image"),
    ("flp", "FL Studio project"), ("fls", "FARO scan"), ("flv", "Flash video"),
    ("fm", "FrameMaker document"), ("fm2", "FCEUX movie"), ("fna", "FASTA nucleotides"),
    ("fodg", "Flat ODF Graphics"), ("fodp", "Flat ODF Presentation"),
    ("fods", "Flat ODF Spreadsheet"), ("fodt", "Flat ODF Text"), ("fpf", "FLIR thermal image"),
    ("fq", "FASTQ reads"), ("frag", "GLSL Fragment Shader"), ("fs", "GLSL fragment shader"),
    ("fsb", "FMOD sound bank"), ("fsh", "OpenGL Fragment Shader"), ("fsproj", "F# project"),
    ("fts", "Astronomy image (FITS)"), ("fws", "FARO scan workspace"), ("g", "G-code"),
    ("gb", "Game Boy ROM"), ("gba", "Game Boy Advance ROM"), ("gbc", "Game Boy Color ROM"),
    ("gbl", "Gerber bottom layer"), ("gbr", "Gerber PCB"), ("gbs", "Game Boy sound"),
    ("gco", "G-code"), ("gcode", "G-code"), ("gcsv", "Gyroflow IMU log"),
    ("gdb", "Esri geodatabase"), ("gem", "RubyGem"), ("gen", "Mega Drive ROM"),
    ("geojson", "GeoJSON"), ("geom", "GLSL Geometry Shader"), ("gg", "Game Gear ROM"),
    ("gguf", "GGUF model"), ("gh", "Grasshopper definition"),
    ("ghx", "Grasshopper definition (XML)"), ("gi", "Source 2 game info (gameinfo.gi)"),
    ("gif", "GIF image"), ("gifv", "GIF-style video"), ("gig", "GigaStudio instrument"),
    ("gitattributes", "Git Attributes"), ("gitignore", "Git Ignore Rules"),
    ("gitmodules", "Git Submodules"), ("glb", "glTF binary (GLB)"),
    ("glif", "UFO glyph (GLIF)"), ("glsl", "GLSL Shader"), ("gltf", "glTF 3D model"),
    ("gml", "Geography Markup Language"), ("gmx", "GameMaker resource (legacy)"),
    ("go", "Go Source"), ("godot", "Godot project"), ("gpg", "GnuPG file"),
    ("gpkg", "GeoPackage"), ("gpr", "GoPro RAW"), ("gpt", "GUID Partition Table"),
    ("gpx", "GPS track (GPX)"), ("gql", "GraphQL schema"), ("gradle", "Gradle build script"),
    ("graphql", "GraphQL schema"), ("grb", "GRIB weather data"), ("grd", "Photoshop gradients"),
    ("grib", "GRIB weather data"), ("grib2", "GRIB2 weather data"), ("groovy", "Groovy Source"),
    ("gs", "GLSL geometry shader"), ("gsm", "GSM audio"), ("gtl", "Gerber top layer"),
    ("gxf", "General Exchange Format"), ("gz", "GZip archive"), ("h", "C / C++ Header"),
    ("h264", "H.264 stream"), ("h265", "H.265 stream"), ("h2v", "MPEG-2 stream"),
    ("har", "HTTP Archive"), ("hash", "Hash / checksum"), ("hcl", "HashiCorp config"),
    ("hdd", "Parallels virtual disk"), ("hdp", "HD Photo (JPEG XR)"), ("hdr", "Radiance HDR"),
    ("hea", "PhysioNet header"), ("heic", "HEIC photo"), ("heif", "HEIF photo"),
    ("hevc", "HEVC stream"), ("hex", "Intel HEX"), ("hfthumb", "House Flipper thumbnail"),
    ("hgt", "SRTM elevation"), ("hh", "C++ Header"), ("hip", "Houdini scene"),
    ("hipnc", "Houdini (non-commercial)"), ("hive", "Windows registry hive"),
    ("hjson", "Human JSON"), ("hlsl", "HLSL Shader"), ("hmm", "Objective-C++ header"),
    ("hpp", "C++ Header"), ("htm", "HTML document"), ("html", "HTML page"),
    ("hwp", "Hancom Hangul"), ("hwpx", "Hancom HWPX"), ("hxx", "C++ Header"),
    ("iam", "Inventor assembly"), ("ibooks", "iBooks Author book"), ("ical", "iCalendar event"),
    ("icb", "Truevision TGA"), ("icns", "Apple icon"), ("ico", "Windows icon"),
    ("ics", "iCalendar event"), ("icu", "ICU Data"), ("idea", "ideaMaker project"),
    ("idl", "Interface Definition file"), ("idml", "InDesign Markup"),
    ("idw", "Inventor drawing"), ("idx", "Git pack index"), ("ifb", "iCalendar free/busy"),
    ("ifc", "IFC building model"), ("ifczip", "Zipped IFC model"), ("igc", "Glider flight log"),
    ("iges", "IGES CAD model"), ("igs", "IGES CAD model"), ("iiq", "Phase One RAW"),
    ("il2cppmeta", "IL2CPP global metadata"), ("ima", "Floppy disk image"),
    ("imc", "GetDataBack Compressed Image"), ("img", "Raw disk image"),
    ("imga", "Marathon / Aleph One images"), ("imy", "iMelody ringtone"),
    ("in", "Autoconf Template"), ("inc", "Include File"), ("indd", "InDesign document"),
    ("indt", "InDesign template"), ("inf", "Windows Setup Information"),
    ("info", "Info Text File"), ("ini", "INI config"),
    ("innouninstall", "Inno Setup uninstall log"), ("ino", "Arduino Sketch"),
    ("inp", "FEA input deck"), ("insp", "Insta360 photo"), ("insv", "Insta360 video"),
    ("ioc", "OpenIOC indicator"), ("ipa", "iOS app"), ("ipc", "IPC-D-356 netlist"),
    ("ips", "IPS ROM patch"), ("ipt", "Inventor part"), ("ipynb", "Jupyter Notebook"),
    ("ism", "Smooth Streaming manifest"), ("ismc", "Smooth Streaming client manifest"),
    ("iso", "ISO disc image"), ("isz", "Compressed ISO"), ("it", "Impulse Tracker module"),
    ("itb", "U-Boot FIT image"), ("ivf", "IVF video"), ("j2c", "JPEG 2000 codestream"),
    ("j2k", "JPEG 2000 codestream"), ("j64", "Atari Jaguar ROM"),
    ("jam", "Boost.Jam build script"), ("jar", "Java Archive"),
    ("jats", "Journal Article Tag Suite"), ("java", "Java Source"), ("jb2", "JBIG2 image"),
    ("jbig", "JBIG image"), ("jbig2", "JBIG2 image"), ("jcal", "jCal calendar"),
    ("jcard", "jCard contact"), ("jceks", "Java JCEKS keystore"), ("jdx", "JCAMP-DX spectrum"),
    ("jffs2", "JFFS2 flash image"), ("jfif", "JPEG image (JFIF)"), ("jgw", "JPEG world file"),
    ("jif", "JPEG image (JIF)"), ("jks", "Java KeyStore"), ("jnlp", "Java Web Start"),
    ("job", "Scheduled task"), ("jp2", "JPEG 2000"), ("jpc", "JPEG 2000 codestream"),
    ("jpeg", "JPEG image"), ("jpf", "JPEG 2000 (JPX)"), ("jpg", "JPEG image"),
    ("jpx", "JPEG 2000 (JPX)"), ("js", "JavaScript"), ("json", "JSON data"), ("json5", "JSON5"),
    ("jsonc", "JSON with Comments"), ("jsonl", "JSON Lines"), ("jsx", "JavaScript + JSX"),
    ("jt", "JT 3D model"), ("jwt", "JSON Web Token"), ("jxl", "JPEG XL image"),
    ("jxr", "JPEG XR"), ("kdb", "KeePass 1.x database"), ("kdbx", "KeePass database"),
    ("kdc", "Kodak RAW (KDC)"), ("key", "Cryptographic key"), ("keychain", "Apple Keychain"),
    ("keynote", "Apple Keynote presentation"), ("keystore", "Java KeyStore"),
    ("kfx", "Kindle KFX e-book"), ("kicad_mod", "KiCad footprint"), ("kicad_pcb", "KiCad PCB"),
    ("kicad_prl", "KiCad local settings"), ("kicad_pro", "KiCad project"),
    ("kicad_sch", "KiCad schematic"), ("kicad_sym", "KiCad symbol library"),
    ("kml", "Google Earth (KML)"), ("kmz", "Zipped Google Earth"),
    ("known_hosts", "OpenSSH known_hosts"), ("kra", "Krita document"),
    ("ksplat", "Compressed Gaussian splat"), ("kt", "Kotlin Source"), ("kts", "Kotlin Script"),
    ("ktx", "Khronos texture"), ("ktx2", "Khronos texture v2"), ("kv3", "Valve KeyValues3"),
    ("lang", "Language Strings"), ("las", "LiDAR point cloud"), ("latex", "LaTeX document"),
    ("laz", "Compressed LiDAR"), ("ldb", "LevelDB table"), ("ldi", "LDIF directory export"),
    ("ldif", "LDAP data export"), ("ldtk", "LDtk level"), ("less", "Less stylesheet"),
    ("lesser", "LGPL licence text"), ("lha", "LHA archive"), ("lib", "Static / import library"),
    ("lit", "Microsoft Reader e-book"), ("litematic", "Litematica schematic"),
    ("lng", "Language File"), ("lnk", "Windows shortcut"), ("lnx", "Atari Lynx ROM"),
    ("lock", "Dependency lockfile"), ("locmeta", "Unreal Localization Metadata"),
    ("locres", "Unreal Localization Resource"), ("log", "Log file"),
    ("logic", "Logic Pro project"), ("logicx", "Logic Pro X project"),
    ("look", "SpeedGrade look"), ("lottie", "Lottie animation"), ("love", "LÖVE game"),
    ("lrc", "Synced lyrics"), ("lrcat", "Lightroom catalog"), ("lrf", "Sony BBeB e-book"),
    ("lrtemplate", "Lightroom preset (legacy)"), ("lrv", "Low-res proxy video"),
    ("lrx", "Sony BBeB e-book (DRM)"), ("lst", "List / Index File"), ("lua", "Lua Script"),
    ("lwo", "LightWave object"), ("lws", "LightWave scene"), ("lxf", "Leitch broadcast video"),
    ("lyr", "ArcMap layer"), ("lyrx", "ArcGIS Pro layer"), ("lz4", "LZ4 stream"),
    ("lzh", "LHA archive"), ("lzma", "LZMA stream"), ("lzo", "LZO stream"),
    ("m1v", "MPEG-1 video"), ("m2p", "MPEG-2 program stream"),
    ("m2t", "MPEG-2 transport stream"), ("m2ts", "AVCHD video (M2TS)"), ("m2v", "MPEG-2 video"),
    ("m3u", "M3U playlist"), ("m3u8", "UTF-8 playlist / HLS"), ("m4", "M4 Macro File"),
    ("m4a", "M4A audio"), ("m4b", "M4B audiobook"), ("m4r", "iPhone ringtone"),
    ("ma", "Maya scene (ASCII)"), ("mab", "Mozilla address book"),
    ("maff", "Mozilla Archive Format"), ("mak", "Makefile"), ("make", "Makefile"),
    ("man", "Unix manual page"), ("map", "Source map"), ("mat", "MATLAB data"),
    ("max", "3ds Max scene"), ("mb", "Maya scene (binary)"), ("mbox", "Mailbox file"),
    ("mbr", "Master Boot Record"), ("mbtiles", "MBTiles map"), ("mbx", "Eudora mailbox"),
    ("mca", "Minecraft region"), ("mcaddon", "Minecraft Bedrock add-on"),
    ("mcmeta", "Minecraft Asset Metadata"), ("mcpack", "Minecraft Bedrock pack"),
    ("mcr", "Minecraft region (legacy)"), ("mctemplate", "Minecraft world template"),
    ("mcworld", "Minecraft world"), ("md", "Markdown"), ("md2", "Quake II model"),
    ("md3", "Quake III model"), ("mdb", "Access database (legacy)"),
    ("mdf", "Media disc image"), ("mdl", "Quake/Half-Life model"),
    ("mdp", "MediBang Paint Document"), ("mds", "Media Descriptor"), ("med", "OctaMED module"),
    ("mef", "Mamiya RAW"), ("meta", "Unity meta file"), ("mf", "OVF manifest"),
    ("mht", "Web archive (MHT)"), ("mhtml", "Web archive (MHTML)"), ("mid", "MIDI sequence"),
    ("midi", "MIDI sequence"), ("mif", "MapInfo Interchange"), ("minipsf", "Miniature PSF"),
    ("mixer", "Unity audio mixer"), ("mjs", "JavaScript module"), ("mk", "Makefile Fragment"),
    ("mka", "Matroska audio"), ("mks_template", "Source 2 sheet template"),
    ("mkv", "Matroska video"), ("mlp", "Meridian Lossless Packing"),
    ("mm", "Objective-C++ source"), ("mmcif", "Macromolecular CIF"), ("mmd", "OctaMED module"),
    ("mmf", "Yamaha SMAF"), ("mml", "Aleph One MML config"),
    ("mng", "MNG animation (PNG family)"), ("mo3", "MO3 compressed module"),
    ("mobi", "Mobipocket e-book"), ("mobileconfig", "Apple configuration profile"),
    ("mobileprovision", "iOS provisioning profile"), ("mod", "Amiga module"),
    ("model", "CATIA V4 model"), ("mogrt", "Motion Graphics Template"), ("mol", "MDL Molfile"),
    ("mol2", "Tripos molecule"), ("mos", "Leaf RAW"), ("mot", "Motorola S-record"),
    ("mov", "QuickTime video"), ("mp+", "Musepack audio"), ("mp1", "MPEG-1 Layer I audio"),
    ("mp2", "MPEG-1 Layer II audio"), ("mp3", "MP3 audio"), ("mp4", "MP4 video"),
    ("mpc", "Musepack"), ("mpd", "MPEG-DASH manifest"), ("mpeg", "MPEG video"),
    ("mpg", "MPEG video"), ("mpk", "MessagePack"), ("mpkg", "macOS meta-package"),
    ("mpo", "MPO 3D photo"), ("mpp", "Musepack audio"), ("mpq", "Blizzard MPQ archive"),
    ("mpv", "MPEG video stream"), ("mqa", "MQA audio"), ("mrw", "Minolta RAW"),
    ("msf", "Mozilla mail index"), ("msg", "Outlook message"), ("msgpack", "MessagePack"),
    ("msh", "Gmsh mesh"), ("msi", "Windows installer"), ("msix", "Windows app package (MSIX)"),
    ("msu", "Windows Update package"), ("mtl", "MTL material library"),
    ("mtm", "MultiTracker module"), ("mts", "AVCHD video"), ("mxf", "Material Exchange Format"),
    ("n64", "Nintendo 64 ROM"), ("nbt", "Minecraft NBT data"), ("nc", "CNC G-code"),
    ("nc4", "NetCDF-4 data"), ("ndjson", "Newline-delimited JSON"), ("nds", "Nintendo DS ROM"),
    ("nef", "Nikon RAW"), ("nes", "NES ROM"), ("net", "SPICE netlist"), ("nfo", "Info file"),
    ("ngc", "LinuxCNC G-code"), ("nii", "NIfTI brain scan"), ("ninja", "Ninja Build File"),
    ("nksc", "Nikon NX Studio sidecar"), ("nmea", "NMEA GPS log"),
    ("nmea0183", "NMEA 0183 GPS log"), ("node", "Native add-on module (.node)"),
    ("npmignore", "npm Ignore Rules"), ("npy", "NumPy array"), ("npz", "Zipped NumPy arrays"),
    ("nrg", "Nero disc image"), ("nrw", "Nikon RAW (NRW)"), ("nsf", "HCL Notes database"),
    ("nsfe", "Extended NES sound"), ("nsp", "Switch package"), ("ntar", "pcapng capture"),
    ("numbers", "Apple Numbers spreadsheet"), ("nupkg", "NuGet package"),
    ("nut", "NUT container"), ("nvram", "VM firmware memory"), ("nwc", "Navisworks cache"),
    ("nwd", "Navisworks model"), ("nwf", "Navisworks file set"), ("nxml", "PubMed article XML"),
    ("o", "Object file"), ("o5c", "OpenStreetMap change"), ("o5m", "OpenStreetMap o5m"),
    ("obb", "Android OBB expansion file"), ("obj", "OBJ 3D model"), ("obu", "AV1 video stream"),
    ("odg", "OpenDocument graphics"), ("odp", "OpenDocument presentation"),
    ("ods", "OpenDocument spreadsheet"), ("odt", "OpenDocument text"), ("off", "OFF 3D model"),
    ("ofr", "OptimFROG"), ("ofs", "OptimFROG DualStream"), ("oft", "Outlook template"),
    ("ogg", "Ogg audio"), ("ogm", "Ogg Media"), ("ogv", "Ogg video"),
    ("okt", "Oktalyzer module"), ("old", "Backup File"), ("olm", "Outlook for Mac archive"),
    ("onnx", "ONNX neural-network model"), ("oodledict", "Oodle-compressed data (REDengine)"),
    ("opml", "Outline (OPML)"), ("opus", "Opus audio"), ("opvault", "1Password OPVault"),
    ("orc", "ORC columnar data"), ("orf", "Olympus RAW"), ("org", "Org mode"),
    ("osm", "OpenStreetMap data"), ("ost", "Outlook offline cache"), ("otf", "OpenType font"),
    ("otg", "OpenDocument graphics template"), ("otio", "OpenTimelineIO"),
    ("otp", "OpenDocument presentation template"), ("ots", "OpenDocument spreadsheet template"),
    ("ott", "OpenDocument text template"), ("ova", "OVF appliance"),
    ("overridecontroller", "Unity Animator Override Controller"),
    ("ovf", "Open Virtualization Format"), ("ovpn", "OpenVPN config"), ("oxps", "OpenXPS"),
    ("p12", "PKCS#12 keystore"), ("p65", "PageMaker 6.5 layout"),
    ("p7b", "PKCS#7 certificate bundle"), ("p7c", "PKCS#7 certificate bundle"),
    ("p7m", "S/MIME encrypted email"), ("p7s", "S/MIME signature"),
    ("p8", "PKCS#8 private key"), ("pab", "Personal Address Book"), ("pack", "Git pack file"),
    ("package", "The Sims package"), ("pages", "Apple Pages document"),
    ("pak", "Game data pack"), ("pam", "Portable Arbitrary Map"), ("par", "Solid Edge part"),
    ("parquet", "Apache Parquet"), ("part", "Partial download"), ("pat", "Photoshop patterns"),
    ("patch", "Patch file"), ("pb", "Protocol Buffers data"), ("pbf", "OSM/vector tile binary"),
    ("pbm", "Portable Bitmap"), ("pc", "pkg-config file"), ("pcap", "Packet capture"),
    ("pcapng", "Packet capture (next gen)"), ("pcbdoc", "Altium PCB"),
    ("pcblib", "Altium footprint library"), ("pcd", "Point Cloud Data"),
    ("pce", "PC Engine ROM"), ("pck", "Godot resource pack"), ("pct", "Apple PICT"),
    ("pcx", "PCX image"), ("pd_", ".NET assembly metadata (renamed)"), ("pdf", "PDF document"),
    ("pdn", "Paint.NET image"), ("pdsbak", "Proteus Design Backup"), ("pef", "Pentax RAW"),
    ("pem", "PEM certificate / key"), ("penc", "Samsung encrypted package"),
    ("pf", "Windows Prefetch"), ("pfx", "PKCS#12 keystore"), ("pgm", "Portable Graymap"),
    ("pgp", "OpenPGP message"), ("pgw", "PNG world file"), ("php", "PHP Source"),
    ("phya", "Marathon / Aleph One physics"), ("phys", "Marathon / Aleph One physics"),
    ("physicmaterial", "Unity physics material"),
    ("physicsmaterial2d", "Unity 2D physics material"), ("pickle", "Python pickle"),
    ("pict", "Apple PICT"), ("pk3", "Quake III archive"), ("pk4", "id Tech 4 archive"),
    ("pkf", "DJI Waveform Peak File"), ("pkg", "macOS installer"), ("pkl", "Python pickle"),
    ("pl", "Perl Source"), ("pla", "Graphisoft ArchiCAD Archive"), ("plist", "Property list"),
    ("pln", "Graphisoft ArchiCAD Project"), ("pls", "PLS playlist"), ("ply", "PLY 3D model"),
    ("pm", "Perl Module"), ("pm6", "PageMaker 6 layout"), ("pmd", "PageMaker layout"),
    ("pmtiles", "PMTiles map archive"), ("png", "PNG image"), ("pnm", "Portable Anymap"),
    ("po", "gettext translation (PO)"), ("pol", "Group Policy file"),
    ("poscar", "VASP structure"), ("pot", "gettext template (POT)"),
    ("potm", "PowerPoint macro-enabled template"), ("potx", "PowerPoint template"),
    ("pp3", "RawTherapee sidecar"), ("ppf", "PlayStation patch"), ("ppk", "PuTTY private key"),
    ("ppm", "Portable Pixmap"), ("ppsm", "PowerPoint macro-enabled slideshow"),
    ("ppsx", "PowerPoint slideshow"), ("ppt", "PowerPoint 97-2003 presentation"),
    ("pptm", "PowerPoint macro-enabled presentation"), ("pptx", "PowerPoint presentation"),
    ("prc", "PRC 3D data"), ("prefab", "Unity prefab"), ("prel", "Premiere Elements project"),
    ("prettierignore", "Prettier Ignore Rules"), ("pri", "qmake Include"),
    ("prj", "Projection file"), ("prjpcb", "Altium project"), ("pro", "qmake Project"),
    ("procreate", "Procreate artwork"), ("properties", "Java properties"),
    ("proto", "Protocol Buffers schema"), ("prproj", "Premiere Pro project"),
    ("prt", "CAD part file"), ("ps", "PostScript"), ("ps1", "PowerShell script"),
    ("psb", "Photoshop big document"), ("psd", "Photoshop document"),
    ("psd1", "PowerShell data file"), ("psf", "Portable Sound Format"),
    ("psf2", "Portable Sound Format 2"), ("psm", "Solid Edge sheet metal"),
    ("psm1", "PowerShell module"), ("pst", "Outlook data file"), ("pt6", "PageMaker template"),
    ("pts", "Point cloud (PTS)"), ("ptx", "Pro Tools session"), ("pub", "Public key"),
    ("pvk", "Microsoft private key"), ("pvm", "Parallels VM"), ("pwd", "Solid Edge weldment"),
    ("pxd", "Cython definition file"), ("pxi", "Cython include"), ("pxn", "Logitech raw photo"),
    ("py", "Python Source"), ("pyc", "Python bytecode"), ("pyd", "Python Extension Module"),
    ("pyf", "F2PY interface (Fortran/Python)"), ("pyi", "Python type stub"),
    ("pys", "Python script"), ("pythonpath", "Python path configuration (.pth)"),
    ("pyw", "Python Source"), ("pyx", "Cython Source"), ("pyxel", "Pyxel Edit document"),
    ("qb", "Qubicle voxel model"), ("qcow2", "QEMU virtual disk"),
    ("qcp", "Qualcomm PureVoice"), ("qgs", "QGIS project"), ("qgz", "QGIS project (zipped)"),
    ("qmd", "Quarto document"), ("qoi", "Quite OK Image"), ("qrc", "Qt Resource Collection"),
    ("qss", "Qt style sheet"), ("qxd", "QuarkXPress layout"), ("qxp", "QuarkXPress project"),
    ("r", "R Source"), ("r3d", "REDCODE raw video"), ("raf", "Fujifilm RAW"),
    ("rar", "RAR archive"), ("ras", "Sun Raster"), ("raw", "Camera RAW"), ("rb", "Ruby Source"),
    ("rc", "Resource Script"), ("rda", "R workspace"), ("rdata", "R workspace"),
    ("rdb", "Redis snapshot"), ("rds", "R data object"), ("readme", "Readme file"),
    ("rec", "Recording / session file"), ("redscripts", "REDengine compiled scripts"),
    ("redshadercache", "REDengine shader cache"), ("reg", "Windows Registry export"),
    ("resource", "Unity resource"), ("ress", "Unity Resource Stream"),
    ("rev", "Git pack reverse index"), ("rf64", "RF64 broadcast WAV"), ("rfa", "Revit family"),
    ("rft", "Revit family template"), ("rgss3a", "RPG Maker VX Ace archive"),
    ("rgssad", "RPG Maker archive"), ("rm", "RealMedia"), ("rmd", "R Markdown"),
    ("rmi", "RMID MIDI"), ("rmvb", "RealMedia Variable Bitrate"),
    ("rne", "Renamed DLL (REDengine / Cyberpunk)"), ("rng", "RELAX NG schema"),
    ("rom", "Firmware/ROM image"), ("romfs", "romfs image"), ("rpa", "Ren’Py archive"),
    ("rpm", "RPM package"), ("rpp", "REAPER project"), ("rpp-bak", "Reaper project backup"),
    ("rpyc", "Ren’Py compiled script"), ("rs", "Rust Source"),
    ("rsp", "Compiler response file"), ("rss", "RSS feed"), ("rst", "reStructuredText"),
    ("rte", "Revit template"), ("rtf", "Rich Text Format"), ("rtfd", "macOS rich text"),
    ("rtttl", "Nokia ringtone"), ("rtx", "RTTTL ringtone"), ("rules", "IDS rules"),
    ("rvdata2", "RPG Maker VX Ace data"), ("rvt", "Revit project"), ("rw2", "Panasonic RAW"),
    ("rwl", "Leica RAW"), ("rwz", "Rawzor raw photo"), ("rxdata", "RPG Maker XP data"),
    ("s19", "Motorola S-record"), ("s28", "Motorola S-record"), ("s37", "Motorola S-record"),
    ("s3m", "Scream Tracker 3 module"), ("safetensors", "Safetensors weights"),
    ("sam", "Sequence alignment map"), ("sample", "Git Hook Sample"),
    ("sap", "Atari SAP music"), ("sarif", "SARIF results"), ("sas7bdat", "SAS dataset"),
    ("sat", "ACIS model (SAT)"), ("sav", "SPSS dataset"), ("saz", "Fiddler capture"),
    ("sbn", "Shapefile spatial index"), ("sbs", "Substance Designer source"),
    ("sbsar", "Substance material"), ("sbx", "Shapefile spatial index"),
    ("sc2replay", "StarCraft II replay"), ("scala", "Scala Source"),
    ("scd", "Scribus document"), ("scea", "Marathon / Aleph One scenario"),
    ("scen", "Marathon / Aleph One scenario"), ("sch", "Circuit schematic"),
    ("schdoc", "Altium schematic"), ("schem", "Minecraft schematic (Sponge)"),
    ("schematic", "Minecraft schematic"), ("schlib", "Altium schematic library"),
    ("scr", "Windows screensaver"), ("script", "REDengine / redscript source"),
    ("scriv", "Scrivener project"), ("scrivx", "Scrivener project"),
    ("scss", "Sass stylesheet (SCSS)"), ("sct", "Windows Script Component"),
    ("sdb", "Application shim database"), ("sdc", "StarOffice Calc"),
    ("sdd", "StarOffice Impress"), ("sdf", "Structure-data file"), ("sdw", "StarOffice Writer"),
    ("segy", "SEG-Y seismic"), ("service", "systemd service unit"),
    ("session", "CATIA session"), ("sesx", "Audition session"), ("set", "EEGLAB dataset"),
    ("sf2", "SoundFont 2"), ("sf3", "Compressed SoundFont"), ("sfark", "sfArk SoundFont"),
    ("sfc", "Super Famicom ROM"), ("sfs", "SquashFS image"), ("sfz", "SFZ instrument"),
    ("sgi", "SGI image"), ("sgy", "SEG-Y seismic"), ("sh", "Shell Script"),
    ("shader", "Shader (ShaderLab / GPU shader)"),
    ("shadervariants", "Unity shader variant collection"), ("shn", "Shorten audio"),
    ("shp", "Shapefile"), ("shpa", "Marathon / Aleph One shapes"),
    ("shps", "Marathon / Aleph One shapes"), ("shx", "Shapefile index"), ("sid", "MrSID image"),
    ("sig", "Digital signature"), ("signatures", "Source 2 function signatures"),
    ("simg", "Android sparse image"), ("sit", "StuffIt archive"), ("sitx", "StuffIt X archive"),
    ("skel", "Spine skeleton (binary)"), ("sketch", "Sketch design"),
    ("skip", "Skipped-test marker"), ("skp", "SketchUp model"), ("sla", "Scribus document"),
    ("sldasm", "SolidWorks assembly"), ("slddrw", "SolidWorks drawing"),
    ("sldprt", "SolidWorks part"), ("sldreg", "SolidWorks settings backup"),
    ("sln", "Visual Studio solution"), ("slnx", "Visual Studio solution (XML)"),
    ("smc", "SNES ROM"), ("smd", "Mega Drive ROM"), ("sms", "Master System ROM"),
    ("snap", "Snap package"), ("snb", "Shanda Bambook e-book"), ("snd", "NeXT/Sun sound"),
    ("snda", "Marathon / Aleph One sounds"), ("sndz", "Marathon / Aleph One sounds"),
    ("so", "Shared library"), ("sp", "SPICE netlist"), ("spc", "SNES music rip"),
    ("spec", "Spec File"), ("spi", "SPICE netlist"), ("spice", "SPICE simulation"),
    ("spine", "Spine skeleton"), ("splat", "Gaussian splat scene"),
    ("spp", "Substance Painter project"), ("spriteatlas", "Unity sprite atlas"),
    ("spx", "Speex audio"), ("spz", "Compressed Gaussian splat"), ("sql", "SQL script"),
    ("sqlite", "SQLite database"), ("sqlite-shm", "SQLite shared-memory index"),
    ("sqlite-wal", "SQLite write-ahead log"), ("sqlite3", "SQLite database"),
    ("sqlite3-shm", "SQLite shared-memory index (.sqlite3 sidecar)"),
    ("sqlite3-wal", "SQLite write-ahead log (.sqlite3 sidecar)"),
    ("squashfs", "SquashFS image"), ("sr2", "Sony RAW (SR2)"), ("srec", "Motorola S-record"),
    ("srf", "Sony RAW (SRF)"), ("srm", "Emulator save"), ("srt", "SubRip subtitles"),
    ("srw", "Samsung RAW"), ("ssa", "SSA subtitles"), ("stamp", "Build stamp / marker"),
    ("state", "Emulator savestate"), ("static", "Static Asset / Fixture"),
    ("step", "STEP CAD model"), ("stix", "STIX threat intel"), ("stl", "STL 3D model"),
    ("stm", "Scream Tracker 2 module"), ("stp", "STEP CAD model"), ("sty", "LaTeX style"),
    ("sub", "SUB subtitles"), ("sun", "Sun Raster"),
    ("svap", "SOLIDWORKS Visualize appearance"), ("svelte", "Svelte component"),
    ("svg", "SVG vector image"), ("svpj", "SOLIDWORKS Visualize project"),
    ("swf", "Flash movie"), ("swift", "Swift Source"), ("swm", "Split WIM image"),
    ("sxc", "OpenOffice.org Calc"), ("sxd", "StarOffice Draw"), ("sxi", "StarOffice Impress"),
    ("sxw", "OpenOffice.org Writer"), ("tab", "MapInfo table"), ("tak", "TAK lossless audio"),
    ("tap", "CNC G-code (TAP)"), ("tar", "TAR archive"), ("tbz", "bzip2 tarball"),
    ("tcr", "Psion e-book"), ("tcx", "Garmin Training Center"),
    ("tdms", "LabVIEW measurement data"), ("tei", "TEI document"),
    ("template", "Text Template"), ("tex", "TeX source"), ("textile", "Textile markup"),
    ("tf", "Terraform config"), ("tfstate", "Terraform state"), ("tfw", "TIFF world file"),
    ("tga", "Targa image"), ("tgz", "Gzipped TAR archive"), ("thd", "Dolby TrueHD"),
    ("thm", "Camera thumbnail"), ("thrift", "Apache Thrift"),
    ("thumbsdb", "Windows thumbnail cache"), ("tic", "TIC-80 cartridge"),
    ("tiff", "TIFF image"), ("tlz", "LZMA tarball"), ("tmj", "Tiled map (JSON)"),
    ("tmx", "Tiled map"), ("toc", "Eudora index"), ("toml", "TOML config"),
    ("topojson", "TopoJSON"), ("torrent", "BitTorrent file"), ("tp", "PVR/DVB recording"),
    ("tps", "Unreal Third-Party Notice"), ("tres", "Godot resource"),
    ("trp", "HD transport stream"), ("truehd", "Dolby TrueHD"), ("trx", "Router firmware"),
    ("ts", "Transport stream / TypeScript"), ("tscn", "Godot scene"), ("tsj", "Tiled tileset"),
    ("tsv", "TSV table"), ("tsx", "TypeScript + JSX"), ("tta", "True Audio"),
    ("ttc", "TrueType collection"), ("ttf", "TrueType font"),
    ("tweak", "REDengine TweakXL source"), ("txt", "Plain text"),
    ("txz", "XZ-compressed tarball"), ("tz", "Compressed tarball"),
    ("tzf", "Terrestrial scan (TZF)"), ("tzst", "Zstandard tarball"), ("u3d", "Universal 3D"),
    ("uasset", "Unreal Engine asset"), ("ubi", "UBI flash volume"),
    ("ubifs", "UBIFS flash image"), ("ubulk", "Unreal Bulk Data"),
    ("ucas", "Unreal IoStore data"), ("uexp", "Unreal asset data"),
    ("uf2", "USB Flashing Format"), ("ufont", "Unreal Font"), ("uimage", "U-Boot image"),
    ("umap", "Unreal Engine map"), ("umd", "PSP disc image (UMD)"),
    ("umx", "Unreal Music Package"), ("unity", "Unity scene"),
    ("unitymanifest", "Unity asset bundle manifest"), ("unitypackage", "Unity package"),
    ("uplugin", "Unreal Engine Plugin"), ("uproject", "Unreal Engine Project"),
    ("ups", "UPS ROM patch"), ("url", "Internet shortcut"),
    ("usd", "Universal Scene Description"), ("usda", "USD scene (text)"),
    ("usdc", "USD (binary)"), ("usdz", "USDZ AR model"),
    ("userprefs", "MonoDevelop user preferences"),
    ("ushaderbytecode", "Unreal Shader Bytecode"), ("usym", "IL2CPP symbol map"),
    ("utoc", "Unreal IoStore index"), ("v64", "Nintendo 64 ROM"),
    ("valveres", "Valve resource / UI layout"), ("vb", "Visual Basic Source"),
    ("vbk", "Veeam backup"), ("vbm", "VisualBoyAdvance movie"), ("vbox", "VirtualBox machine"),
    ("vbproj", "Visual Basic project"), ("vbs", "VBScript"), ("vcard", "vCard contact"),
    ("vcf", "vCard contact"), ("vcfg", "Source 2 config"), ("vcs", "vCalendar event"),
    ("vcxproj", "C++ project"), ("vda", "Truevision TGA"), ("vdb", "OpenVDB volume"),
    ("vdf", "Valve KeyValues"), ("vdi", "VirtualBox disk"), ("veg", "VEGAS Pro project"),
    ("vert", "GLSL Vertex Shader"), ("vf", "VEGAS project"), ("vfd", "Virtual floppy disk"),
    ("vgm", "Video game music log"), ("vgz", "Compressed VGM"), ("vhd", "Virtual hard disk"),
    ("vhdr", "BrainVision header"), ("vhdx", "Virtual hard disk (VHDX)"),
    ("vmdk", "VMware virtual disk"), ("vmem", "VMware memory image"),
    ("vmg", "Nokia SMS backup"), ("vmrk", "BrainVision markers"),
    ("vmsd", "VMware snapshot metadata"), ("vmsn", "VMware snapshot"),
    ("vmt", "Valve material"), ("vmx", "VMware machine"),
    ("vnm_template", "Source 2 node-graph template"), ("vnt", "Phone note (vNote)"),
    ("vob", "DVD video"), ("voc", "Creative Voice"), ("vox", "MagicaVoxel model"),
    ("vpk", "Valve pack"), ("vqlayout", "Source 2 tools layout"), ("vrm", "VRM avatar"),
    ("vrml", "VRML world"), ("vrt", "GDAL virtual raster"), ("vs", "GLSL vertex shader"),
    ("vsc", "Source 2 style colours"), ("vsd", "Visio drawing (legacy)"),
    ("vsdx", "Visio drawing"), ("vsh", "OpenGL Vertex Shader"),
    ("vsix", "Visual Studio extension"), ("vsnd_template", "Source 2 sound-event template"),
    ("vst", "Truevision TGA"), ("vtf", "Valve Texture Format"), ("vti", "VTK image data"),
    ("vtk", "VTK data"), ("vtp", "VTK polygon data"), ("vtr", "VTK rectilinear grid"),
    ("vts", "VTK structured grid"), ("vtt", "WebVTT subtitles"),
    ("vtu", "VTK unstructured grid"), ("w3m", "Warcraft III map"), ("w3x", "Warcraft III map"),
    ("w64", "Sony Wave64"), ("wab", "Windows Address Book"), ("wad", "Doom/Wii WAD"),
    ("war", "Web Application Archive"), ("warc", "Web ARChive"), ("wasm", "WebAssembly"),
    ("wav", "WAV audio"), ("wbmp", "Wireless Bitmap"), ("wdp", "HD Photo (JPEG XR)"),
    ("webloc", "macOS web shortcut"), ("webm", "WebM video"), ("webp", "WebP image"),
    ("wem", "Wwise audio"), ("wfm", "Oscilloscope waveform"), ("wfp", "Filmora project"),
    ("wg", "WireGuard config"), ("whl", "Python wheel"), ("wim", "Windows Imaging Format"),
    ("wings", "Wings 3D model"), ("wld", "World file"), ("wma", "Windows Media Audio"),
    ("wmf", "Windows Metafile"), ("wmv", "Windows Media Video"), ("woff", "Web font (WOFF)"),
    ("woff2", "Web font (WOFF2)"), ("wpd", "WordPerfect document"),
    ("wpl", "Windows Media Player playlist"), ("wps", "Microsoft Works document"),
    ("wpt", "Microsoft Works template"), ("wri", "Windows Write document"),
    ("wrl", "VRML world"), ("ws", "WonderSwan ROM"), ("wsc", "WonderSwan Color ROM"),
    ("wsp", "Filmora project"), ("wtv", "Windows Recorded TV"), ("wv", "WavPack"),
    ("x", "DirectX model"), ("x3d", "X3D scene"), ("x3dv", "X3D (Classic VRML)"),
    ("x3f", "Sigma RAW"), ("x_b", "Parasolid model (binary)"),
    ("x_t", "Parasolid model (text)"), ("xapk", "Android App Bundle"),
    ("xar", "eXtensible ARchive"), ("xbm", "X Bitmap"), ("xcal", "xCal calendar"),
    ("xcard", "xCard contact"), ("xcf", "GIMP image"), ("xci", "Switch cartridge image"),
    ("xd", "Adobe XD design"), ("xdelta", "xdelta patch"), ("xln", "PCB drill file"),
    ("xls", "Excel 97-2003 spreadsheet"), ("xlsb", "Excel binary workbook"),
    ("xlsm", "Excel macro-enabled workbook"), ("xlsx", "Excel spreadsheet"),
    ("xltm", "Excel macro-enabled template"), ("xltx", "Excel template"),
    ("xm", "FastTracker module"), ("xml", "XML data"), ("xmp", "XMP metadata"),
    ("xpi", "Firefox add-on"), ("xpm", "X Pixmap"), ("xps", "XML Paper Specification"),
    ("xsf", "XCrySDen structure"), ("xsl", "XSLT stylesheet"), ("xspf", "XSPF playlist"),
    ("xyz", "XYZ coordinates"), ("xz", "XZ archive"), ("y4m", "YUV4MPEG video"),
    ("yaffs2", "YAFFS2 flash image"), ("yaml", "YAML data"), ("yar", "YARA rule"),
    ("yara", "YARA rule"), ("yarnclean", "Yarn Clean List"), ("ym", "Atari ST chiptune"),
    ("yml", "YAML document"), ("yuv", "Raw YUV video"), ("yy", "GameMaker resource"),
    ("yyp", "GameMaker project"), ("z", "compress (.Z) archive"), ("z64", "Nintendo 64 ROM"),
    ("zabw", "Compressed AbiWord"), ("zae", "Zipped COLLADA"),
    ("zcode", "Zortrax Z-SUITE (compiled print)"), ("zi", "tz database source"),
    ("zip", "ZIP archive"), ("zoo", "Zoo archive"), ("zpr", "ZBrush project"),
    ("zsh", "Zsh Script"), ("zst", "Zstandard archive"), ("ztl", "ZBrush tool"),
];

/// Extension to an index into [`FAMILIES`]. Sorted; see [`lookup`].
#[rustfmt::skip]
static SHELVES: [(&str, u8); 1359] = [
    ("1", 50), ("1pux", 91), ("264", 11), ("265", 11), ("3dm", 61), ("3ds", 61), ("3dsx", 81),
    ("3dxml", 67), ("3fr", 1), ("3g2", 11), ("3ga", 10), ("3gp", 11), ("3mf", 53), ("669", 10),
    ("7z", 69), ("a", 70), ("a26", 81), ("a78", 81), ("aac", 5), ("aae", 3), ("ab", 100),
    ("ab1", 68), ("abbu", 90), ("abc", 98), ("abf", 68), ("abr", 26), ("abw", 32), ("ac", 50),
    ("ac3", 5), ("accdb", 41), ("ace", 70), ("acf", 79), ("aco", 26), ("acv", 26),
    ("addcont_keystone", 82), ("adf", 37), ("adi", 92), ("adoc", 32), ("aep", 14), ("aepx", 20),
    ("aet", 14), ("afdesign", 27), ("aff", 91), ("aff4", 91), ("afl", 98), ("afphoto", 27),
    ("afpub", 27), ("agc", 100), ("ai", 22), ("aiff", 5), ("alp", 8), ("als", 8), ("am", 50),
    ("amf", 53), ("amr", 5), ("ani", 4), ("anim", 76), ("ape", 10), ("apk", 94), ("apkg", 70),
    ("apkm", 94), ("apks", 94), ("appimage", 94), ("appl", 83), ("appx", 70), ("arc", 70),
    ("archive", 82), ("ari", 3), ("arj", 70), ("arrow", 51), ("arw", 1), ("arx", 98),
    ("asar", 70), ("asc", 74), ("asciidoc", 32), ("ase", 80), ("aseprite", 81), ("asf", 21),
    ("asl", 26), ("asm", 61), ("asp", 50), ("aspx", 50), ("ass", 19), ("asset", 76),
    ("assets", 81), ("asx", 21), ("atlas", 81), ("atmos", 9), ("atom", 100), ("au", 10),
    ("aup", 10), ("aup3", 10), ("authorized_keys", 91), ("avc", 11), ("avi", 11), ("avif", 0),
    ("awb", 10), ("awt", 37), ("axf", 99), ("ay", 10), ("azw", 30), ("azw3", 30), ("bak", 47),
    ("bam", 65), ("band", 8), ("bank", 81), ("bash", 50), ("basis", 81), ("bat", 43),
    ("bay", 3), ("bcf", 65), ("bdf", 65), ("bepis", 78), ("bib", 32), ("bie", 98), ("bil", 75),
    ("binwalk", 98), ("bip", 75), ("bk", 100), ("bk2", 77), ("blend", 63), ("bmp", 0),
    ("bnk", 81), ("book", 37), ("bps", 80), ("br", 71), ("braw", 3), ("brd", 61), ("brep", 53),
    ("browser", 47), ("bson", 51), ("bsp", 80), ("bsq", 75), ("build", 50), ("bundle", 81),
    ("bw", 4), ("bw64", 10), ("bwf", 10), ("bz2", 69), ("c", 50), ("c4d", 61), ("cab", 70),
    ("caf", 10), ("cap", 91), ("capnp", 51), ("catpart", 61), ("catproduct", 61), ("cb7", 36),
    ("cba", 37), ("cbor", 51), ("cbr", 36), ("cbt", 36), ("cbz", 36), ("cc", 50), ("ccd", 99),
    ("cdb", 68), ("cdf", 74), ("cdi", 99), ("cdp", 64), ("cdr", 27), ("cdx", 68), ("cdxml", 68),
    ("cer", 87), ("cff", 52), ("cfg", 46), ("cgm", 4), ("cgp", 52), ("cgr", 98), ("chd", 81),
    ("chm", 36), ("chroma", 52), ("cia", 80), ("cif", 65), ("cin", 21), ("cine", 3),
    ("cir", 65), ("cl3", 67), ("clang-format", 50), ("clang-tidy", 50), ("class", 49),
    ("clr", 67), ("cls", 98), ("cmake", 50), ("cmd", 43), ("cnc", 56), ("cnf", 50), ("cnt", 68),
    ("cof", 3), ("comask", 98), ("comp", 50), ("conda", 70), ("conf", 46), ("config", 46),
    ("contact", 88), ("controller", 76), ("cop", 3), ("copying", 50), ("cos", 3), ("cpg", 74),
    ("cpio", 70), ("cpp", 50), ("cpr", 8), ("cpt", 75), ("cr2", 1), ("cr3", 1), ("cramfs", 99),
    ("crash", 100), ("crdownload", 97), ("crl", 89), ("crm", 3), ("crt", 87), ("crw", 1),
    ("crx", 70), ("cs", 50), ("cso", 81), ("csproj", 49), ("csr", 89), ("css", 43), ("csv", 42),
    ("ctg", 95), ("cube", 12), ("cubemap", 76), ("cue", 99), ("cur", 4), ("cursorignore", 50),
    ("cxx", 50), ("dae", 66), ("dart", 50), ("dav", 21), ("db", 45), ("db-shm", 45),
    ("db-wal", 45), ("db3", 45), ("db3-shm", 45), ("db3-wal", 45), ("dbf", 74), ("dbx", 88),
    ("dcm", 65), ("dcr", 1), ("dcs", 1), ("dds", 4), ("deb", 70), ("def", 50), ("der", 87),
    ("desc", 51), ("desktop", 100), ("dff", 10), ("dfu", 101), ("dicom", 65), ("dif", 21),
    ("diff", 49), ("dio", 98), ("dita", 32), ("ditamap", 32), ("divx", 21), ("djv", 29),
    ("djvu", 29), ("dll", 94), ("dls", 10), ("dlv", 67), ("dmg", 94), ("dmp", 91), ("dng", 1),
    ("doc", 31), ("dockerignore", 50), ("docm", 31), ("docx", 31), ("dop", 3), ("dot", 37),
    ("dotm", 31), ("dotx", 31), ("dox", 50), ("doxygen", 50), ("dpx", 21), ("drawio", 57),
    ("drc", 67), ("drl", 65), ("drp", 17), ("drt", 17), ("ds_store", 100), ("dsd", 50),
    ("dsf", 10), ("dsi", 80), ("dsk", 92), ("dsm", 81), ("dsv", 81), ("dsym", 100), ("dt0", 74),
    ("dt1", 74), ("dt2", 74), ("dta", 65), ("dtb", 99), ("dtbo", 99), ("dted", 74), ("dts", 5),
    ("dump", 51), ("dv", 21), ("dvi", 36), ("dvr-ms", 21), ("dwarf", 100), ("dwg", 57),
    ("dwt", 57), ("dx", 65), ("dxf", 57), ("dylib", 52), ("e01", 91), ("e57", 66), ("eac3", 9),
    ("ear", 51), ("ec3", 9), ("ecw", 74), ("edb", 88), ("edf", 65), ("editorconfig", 49),
    ("edl", 13), ("eeg", 68), ("eip", 3), ("elf", 99), ("emf", 4), ("eml", 86), ("emlx", 86),
    ("emz", 4), ("enc", 89), ("entitlements", 50), ("env", 46), ("eot", 38), ("eps", 4),
    ("epsf", 4), ("epsi", 4), ("epub", 31), ("epw", 58), ("erf", 1), ("esd", 99),
    ("eslintignore", 50), ("eslintrc", 50), ("etl", 91), ("evt", 91), ("evtx", 89), ("ewf", 99),
    ("exe", 94), ("exp", 67), ("exr", 4), ("ext", 99), ("ext4", 99), ("f", 50), ("f3d", 54),
    ("f3z", 54), ("f4m", 21), ("f4v", 21), ("f90", 50), ("f95", 50), ("fa", 65), ("faa", 65),
    ("far", 10), ("farbfeld", 4), ("fasta", 65), ("fastq", 65), ("fb2", 32), ("fb3", 36),
    ("fbs", 51), ("fbx", 63), ("fcpxml", 13), ("fd", 101), ("feather", 51), ("ff", 4),
    ("fff", 1), ("fig", 27), ("fila", 83), ("fish", 50), ("fit", 65), ("fits", 65), ("fla", 26),
    ("flac", 5), ("flatpak", 71), ("flif", 4), ("flp", 8), ("fls", 98), ("flv", 11), ("fm", 37),
    ("fm2", 81), ("fna", 65), ("fodg", 31), ("fodp", 31), ("fods", 31), ("fodt", 31),
    ("fpf", 3), ("fq", 65), ("frag", 50), ("fs", 50), ("fsb", 81), ("fsh", 50), ("fsproj", 49),
    ("fts", 65), ("fws", 98), ("g", 56), ("gb", 80), ("gba", 80), ("gbc", 80), ("gbl", 65),
    ("gbr", 65), ("gbs", 10), ("gco", 56), ("gcode", 56), ("gcsv", 15), ("gdb", 74),
    ("gem", 70), ("gen", 80), ("geojson", 72), ("geom", 50), ("gg", 81), ("gguf", 49),
    ("gh", 61), ("ghx", 61), ("gi", 85), ("gif", 0), ("gifv", 21), ("gig", 10),
    ("gitattributes", 50), ("gitignore", 50), ("gitmodules", 50), ("glb", 53), ("glif", 38),
    ("glsl", 50), ("gltf", 53), ("gml", 74), ("gmx", 81), ("go", 50), ("godot", 77),
    ("gpg", 91), ("gpkg", 74), ("gpr", 1), ("gpt", 99), ("gpx", 72), ("gql", 49),
    ("gradle", 49), ("graphql", 49), ("grb", 74), ("grd", 26), ("grib", 74), ("grib2", 74),
    ("groovy", 50), ("gs", 50), ("gsm", 10), ("gtl", 65), ("gxf", 21), ("gz", 69), ("h", 50),
    ("h264", 11), ("h265", 11), ("h2v", 98), ("har", 40), ("hash", 84), ("hcl", 51),
    ("hdd", 101), ("hdp", 4), ("hdr", 4), ("hea", 65), ("heic", 0), ("heif", 0), ("hevc", 11),
    ("hex", 99), ("hfthumb", 84), ("hgt", 74), ("hh", 50), ("hip", 61), ("hipnc", 66),
    ("hive", 91), ("hjson", 40), ("hlsl", 50), ("hmm", 50), ("hpp", 50), ("htm", 43),
    ("html", 43), ("hwp", 36), ("hwpx", 32), ("hxx", 50), ("iam", 61), ("ibooks", 36),
    ("ical", 88), ("icb", 4), ("icns", 4), ("ico", 0), ("ics", 88), ("icu", 47), ("idea", 63),
    ("idl", 50), ("idml", 26), ("idw", 61), ("idx", 44), ("ifb", 88), ("ifc", 66),
    ("ifczip", 66), ("igc", 74), ("iges", 53), ("igs", 53), ("iiq", 1), ("ima", 92),
    ("imc", 92), ("img", 92), ("imga", 83), ("imy", 10), ("in", 50), ("inc", 50), ("indd", 26),
    ("indt", 26), ("inf", 46), ("info", 46), ("ini", 46), ("ino", 50), ("inp", 68),
    ("insp", 21), ("insv", 21), ("ioc", 91), ("ipa", 94), ("ipc", 60), ("ips", 80), ("ipt", 61),
    ("ipynb", 40), ("ism", 21), ("ismc", 21), ("iso", 92), ("isz", 99), ("it", 10),
    ("itb", 101), ("ivf", 21), ("j2c", 4), ("j2k", 4), ("j64", 81), ("jam", 50), ("jar", 51),
    ("jats", 32), ("java", 50), ("jb2", 4), ("jbig", 4), ("jbig2", 4), ("jcal", 90),
    ("jcard", 90), ("jceks", 89), ("jdx", 65), ("jffs2", 99), ("jfif", 0), ("jgw", 74),
    ("jif", 0), ("jks", 89), ("jnlp", 71), ("job", 100), ("jp2", 4), ("jpc", 4), ("jpeg", 0),
    ("jpf", 4), ("jpg", 0), ("jpx", 4), ("js", 43), ("json", 43), ("json5", 40), ("jsonc", 40),
    ("jsonl", 49), ("jsx", 43), ("jt", 66), ("jwt", 49), ("jxl", 0), ("jxr", 4), ("kdb", 91),
    ("kdbx", 89), ("kdc", 1), ("key", 89), ("keychain", 91), ("keynote", 33), ("keystore", 89),
    ("kfx", 36), ("kicad_mod", 59), ("kicad_pcb", 59), ("kicad_prl", 59), ("kicad_pro", 59),
    ("kicad_sch", 59), ("kicad_sym", 59), ("kml", 72), ("kmz", 73), ("known_hosts", 91),
    ("kra", 24), ("ksplat", 67), ("kt", 50), ("kts", 50), ("ktx", 80), ("ktx2", 80),
    ("kv3", 85), ("lang", 77), ("las", 66), ("latex", 32), ("laz", 66), ("ldb", 52),
    ("ldi", 90), ("ldif", 88), ("ldtk", 81), ("less", 50), ("lesser", 50), ("lha", 70),
    ("lib", 70), ("lit", 36), ("litematic", 81), ("lng", 77), ("lnk", 96), ("lnx", 81),
    ("lock", 51), ("locmeta", 77), ("locres", 77), ("log", 48), ("logic", 8), ("logicx", 8),
    ("look", 12), ("lottie", 4), ("love", 80), ("lrc", 6), ("lrcat", 26), ("lrf", 37),
    ("lrtemplate", 26), ("lrv", 21), ("lrx", 37), ("lst", 46), ("lua", 50), ("lwo", 66),
    ("lws", 66), ("lxf", 21), ("lyr", 75), ("lyrx", 75), ("lz4", 69), ("lzh", 70), ("lzma", 69),
    ("lzo", 71), ("m1v", 21), ("m2p", 21), ("m2t", 21), ("m2ts", 11), ("m2v", 21), ("m3u", 21),
    ("m3u8", 21), ("m4", 50), ("m4a", 5), ("m4b", 5), ("m4r", 10), ("ma", 61), ("mab", 90),
    ("maff", 36), ("mak", 50), ("make", 50), ("man", 50), ("map", 49), ("mat", 51), ("max", 61),
    ("mb", 61), ("mbox", 86), ("mbr", 99), ("mbtiles", 74), ("mbx", 90), ("mca", 81),
    ("mcaddon", 81), ("mcmeta", 77), ("mcpack", 81), ("mcr", 81), ("mctemplate", 81),
    ("mcworld", 80), ("md", 43), ("md2", 66), ("md3", 66), ("md5", 32), ("mdb", 41),
    ("mdf", 99), ("mdl", 66), ("mdp", 27), ("mds", 99), ("med", 10), ("mef", 1), ("meta", 76),
    ("mf", 101), ("mht", 32), ("mhtml", 32), ("mid", 7), ("midi", 7), ("mif", 74),
    ("minipsf", 10), ("mixer", 76), ("mjs", 43), ("mk", 50), ("mka", 5), ("mks_template", 85),
    ("mkv", 11), ("mlp", 9), ("mm", 50), ("mmcif", 65), ("mmd", 10), ("mmf", 10), ("mml", 83),
    ("mng", 4), ("mo3", 10), ("mobi", 30), ("mobileconfig", 89), ("mobileprovision", 89),
    ("mod", 10), ("model", 67), ("mogrt", 26), ("mol", 65), ("mol2", 65), ("mos", 1),
    ("mot", 99), ("mov", 11), ("mp+", 10), ("mp1", 10), ("mp2", 10), ("mp3", 5), ("mp4", 11),
    ("mpc", 10), ("mpd", 21), ("mpeg", 11), ("mpg", 11), ("mpk", 51), ("mpkg", 71), ("mpo", 0),
    ("mpp", 10), ("mpq", 80), ("mpv", 21), ("mqa", 10), ("mrw", 1), ("msf", 90), ("msg", 88),
    ("msgpack", 51), ("msh", 68), ("msi", 94), ("msix", 70), ("msu", 71), ("mtl", 53),
    ("mtm", 10), ("mts", 11), ("mxf", 21), ("n64", 80), ("nbt", 80), ("nc", 56), ("nc4", 74),
    ("ndjson", 49), ("nds", 80), ("nef", 1), ("nes", 80), ("net", 68), ("nfo", 35), ("ngc", 56),
    ("nii", 65), ("ninja", 50), ("nksc", 3), ("nmea", 74), ("nmea0183", 74), ("node", 52),
    ("npmignore", 50), ("npy", 49), ("npz", 51), ("nrg", 99), ("nrw", 1), ("nsf", 10),
    ("nsfe", 10), ("nsp", 80), ("ntar", 91), ("numbers", 33), ("nupkg", 70), ("nut", 21),
    ("nvram", 101), ("nwc", 67), ("nwd", 67), ("nwf", 67), ("nxml", 32), ("o", 99), ("o5c", 75),
    ("o5m", 75), ("obb", 81), ("obj", 53), ("obu", 21), ("odg", 31), ("odp", 31), ("ods", 31),
    ("odt", 31), ("off", 53), ("ofr", 10), ("ofs", 98), ("oft", 90), ("ogg", 5), ("ogm", 21),
    ("ogv", 11), ("okt", 10), ("old", 47), ("olm", 90), ("onnx", 52), ("opml", 100),
    ("opus", 5), ("opvault", 91), ("orc", 51), ("orf", 1), ("org", 32), ("osm", 74),
    ("ost", 88), ("otf", 34), ("otg", 31), ("otio", 13), ("otp", 31), ("ots", 31), ("ott", 31),
    ("ova", 99), ("overridecontroller", 76), ("ovf", 99), ("ovpn", 89), ("oxps", 36),
    ("p12", 89), ("p65", 37), ("p7b", 89), ("p7c", 89), ("p7m", 90), ("p7s", 90), ("p8", 89),
    ("pab", 90), ("pack", 44), ("package", 80), ("pages", 33), ("pak", 80), ("pam", 4),
    ("par", 67), ("parquet", 51), ("part", 97), ("pat", 26), ("patch", 49), ("pb", 51),
    ("pbf", 74), ("pbm", 4), ("pc", 50), ("pcap", 89), ("pcapng", 89), ("pcbdoc", 58),
    ("pcblib", 58), ("pcd", 66), ("pce", 81), ("pck", 80), ("pct", 4), ("pcx", 4), ("pd_", 84),
    ("pdf", 28), ("pdn", 24), ("pdsbak", 47), ("pef", 1), ("pem", 87), ("penc", 89), ("pf", 98),
    ("pfx", 89), ("pgm", 4), ("pgp", 91), ("pgw", 74), ("php", 50), ("phya", 83), ("phys", 83),
    ("physicmaterial", 76), ("physicsmaterial2d", 76), ("pickle", 51), ("pict", 4), ("pk3", 80),
    ("pk4", 81), ("pkf", 10), ("pkg", 71), ("pkl", 51), ("pl", 50), ("pla", 67), ("plist", 49),
    ("pln", 67), ("pls", 21), ("ply", 53), ("pm", 50), ("pm6", 37), ("pmd", 36),
    ("pmtiles", 74), ("png", 0), ("pnm", 4), ("po", 50), ("pol", 100), ("poscar", 68),
    ("pot", 50), ("potm", 31), ("potx", 31), ("pp3", 3), ("ppf", 80), ("ppk", 89), ("ppm", 4),
    ("ppsm", 31), ("ppsx", 31), ("ppt", 31), ("pptm", 31), ("pptx", 31), ("prc", 66),
    ("prefab", 76), ("prel", 16), ("prettierignore", 50), ("pri", 50), ("prj", 74),
    ("prjpcb", 58), ("pro", 50), ("procreate", 24), ("properties", 46), ("proto", 49),
    ("prproj", 16), ("prt", 61), ("ps", 4), ("ps1", 43), ("psb", 23), ("psd", 23), ("psd1", 43),
    ("psf", 10), ("psf2", 10), ("psm", 67), ("psm1", 43), ("pst", 88), ("pt6", 37), ("pts", 66),
    ("ptx", 8), ("pub", 89), ("pvk", 91), ("pvm", 101), ("pwd", 67), ("pxd", 50), ("pxi", 50),
    ("pxn", 3), ("py", 50), ("pyc", 49), ("pyd", 47), ("pyf", 50), ("pyi", 50), ("pys", 50),
    ("pyw", 50), ("pyx", 50), ("pyxel", 81), ("qb", 67), ("qcow2", 92), ("qcp", 10),
    ("qgs", 75), ("qgz", 75), ("qmd", 36), ("qoi", 4), ("qrc", 50), ("qss", 85), ("qxd", 36),
    ("qxp", 37), ("r", 50), ("r3d", 3), ("raf", 1), ("rar", 69), ("ras", 4), ("raw", 1),
    ("rb", 50), ("rc", 50), ("rda", 68), ("rdata", 68), ("rdb", 51), ("rds", 68),
    ("readme", 50), ("rec", 93), ("redscripts", 82), ("reg", 89), ("rels", 32), ("res", 85),
    ("resource", 81), ("ress", 77), ("rev", 52), ("rf64", 10), ("rfa", 67), ("rft", 67),
    ("rgss3a", 81), ("rgssad", 81), ("rm", 21), ("rmd", 36), ("rmi", 10), ("rmvb", 21),
    ("rne", 82), ("rng", 50), ("rom", 101), ("romfs", 99), ("rpa", 81), ("rpm", 70), ("rpp", 8),
    ("rpp-bak", 98), ("rpyc", 81), ("rs", 50), ("rsp", 52), ("rss", 100), ("rst", 32),
    ("rte", 67), ("rtf", 32), ("rtfd", 36), ("rtttl", 10), ("rtx", 98), ("rules", 91),
    ("rvdata2", 81), ("rvt", 67), ("rw2", 1), ("rwl", 1), ("rwz", 3), ("rxdata", 81),
    ("s19", 99), ("s28", 99), ("s37", 99), ("s3m", 10), ("safetensors", 49), ("sam", 65),
    ("sample", 50), ("sap", 10), ("sarif", 49), ("sas7bdat", 65), ("sat", 62), ("sav", 65),
    ("saz", 91), ("sbn", 75), ("sbs", 27), ("sbsar", 27), ("sbx", 75), ("sc2replay", 81),
    ("scala", 50), ("scd", 37), ("scea", 83), ("scen", 83), ("sch", 61), ("schdoc", 58),
    ("schem", 81), ("schematic", 81), ("schlib", 58), ("scr", 100), ("script", 82),
    ("scriv", 36), ("scrivx", 37), ("scss", 50), ("sct", 50), ("sdb", 100), ("sdc", 37),
    ("sdd", 37), ("sdf", 65), ("sdw", 37), ("segy", 65), ("service", 100), ("session", 67),
    ("sesx", 26), ("set", 68), ("sf2", 10), ("sf3", 10), ("sfark", 10), ("sfc", 80),
    ("sfs", 99), ("sfz", 10), ("sgi", 4), ("sgy", 65), ("sh", 50), ("shader", 84),
    ("shadervariants", 84), ("shn", 10), ("shp", 74), ("shpa", 83), ("shps", 83), ("shx", 74),
    ("sid", 74), ("sig", 91), ("signatures", 85), ("simg", 101), ("sit", 71), ("sitx", 71),
    ("skel", 81), ("sketch", 27), ("skip", 50), ("skp", 61), ("sla", 37), ("sldasm", 55),
    ("slddrw", 55), ("sldprt", 55), ("sldreg", 61), ("sln", 39), ("slnx", 39), ("smc", 80),
    ("smd", 80), ("sms", 81), ("snap", 71), ("snb", 37), ("snd", 10), ("snda", 83),
    ("sndz", 83), ("so", 99), ("sp", 65), ("spc", 10), ("spec", 50), ("spi", 65), ("spice", 65),
    ("spine", 81), ("splat", 66), ("spp", 27), ("spriteatlas", 76), ("spx", 10), ("spz", 66),
    ("sql", 49), ("sqlite", 45), ("sqlite-shm", 45), ("sqlite-wal", 45), ("sqlite3", 45),
    ("sqlite3-shm", 45), ("sqlite3-wal", 45), ("squashfs", 99), ("sr2", 1), ("srec", 99),
    ("srf", 1), ("srm", 81), ("srt", 19), ("srw", 1), ("ssa", 19), ("stamp", 52), ("state", 81),
    ("static", 50), ("step", 53), ("stix", 91), ("stl", 53), ("stm", 10), ("stp", 53),
    ("sty", 98), ("sub", 19), ("sun", 98), ("svap", 61), ("svelte", 50), ("svg", 25),
    ("svpj", 61), ("swf", 26), ("swift", 50), ("swm", 99), ("sxc", 31), ("sxd", 31),
    ("sxi", 37), ("sxw", 31), ("tab", 74), ("tak", 10), ("tap", 56), ("tar", 69), ("tbz", 71),
    ("tcr", 37), ("tcx", 65), ("tdms", 68), ("tei", 32), ("template", 50), ("tex", 32),
    ("textile", 32), ("tf", 49), ("tfstate", 49), ("tfw", 74), ("tga", 4), ("tgz", 69),
    ("thd", 9), ("thm", 0), ("thrift", 51), ("thumbsdb", 100), ("tic", 81), ("tiff", 0),
    ("tlz", 71), ("tmj", 80), ("tmx", 80), ("toc", 90), ("toml", 46), ("topojson", 74),
    ("torrent", 97), ("tp", 98), ("tps", 47), ("tres", 77), ("trp", 21), ("trx", 101),
    ("ts", 11), ("tscn", 77), ("tsj", 98), ("tsv", 42), ("tsx", 43), ("tta", 10), ("ttc", 34),
    ("ttf", 34), ("tweak", 82), ("txt", 43), ("txz", 71), ("tz", 71), ("tzf", 67), ("tzst", 71),
    ("u3d", 67), ("uasset", 77), ("ubi", 101), ("ubifs", 99), ("ubulk", 77), ("ucas", 81),
    ("uexp", 81), ("uf2", 99), ("ufont", 77), ("uimage", 99), ("umap", 77), ("umd", 81),
    ("umx", 10), ("unity", 76), ("unitypackage", 77), ("uplugin", 77), ("uproject", 77),
    ("ups", 80), ("url", 96), ("usd", 63), ("usda", 63), ("usdc", 66), ("usdz", 63),
    ("userprefs", 39), ("ushaderbytecode", 77), ("usym", 84), ("utoc", 81), ("v64", 80),
    ("vb", 50), ("vbk", 101), ("vbm", 81), ("vbox", 99), ("vbproj", 49), ("vbs", 50),
    ("vcard", 88), ("vcf", 88), ("vcfg", 85), ("vcs", 88), ("vcxproj", 49), ("vda", 98),
    ("vdb", 66), ("vdf", 79), ("vdi", 92), ("veg", 18), ("vert", 50), ("vf", 18), ("vfd", 101),
    ("vgm", 10), ("vgz", 10), ("vhd", 92), ("vhdr", 68), ("vhdx", 92), ("vmdk", 92),
    ("vmem", 99), ("vmg", 90), ("vmrk", 68), ("vmsd", 101), ("vmsn", 99), ("vmt", 80),
    ("vmx", 99), ("vnm_template", 85), ("vnt", 90), ("vob", 11), ("voc", 10), ("vox", 66),
    ("vpk", 80), ("vqlayout", 85), ("vrm", 66), ("vrml", 66), ("vrt", 74), ("vs", 50),
    ("vsc", 85), ("vsd", 67), ("vsdx", 36), ("vsh", 50), ("vsix", 70), ("vsnd_template", 85),
    ("vst", 4), ("vtf", 80), ("vti", 65), ("vtk", 65), ("vtp", 65), ("vtr", 68), ("vts", 68),
    ("vtt", 19), ("vtu", 65), ("w3m", 81), ("w3x", 81), ("w64", 10), ("wab", 90), ("wad", 80),
    ("war", 51), ("warc", 36), ("wasm", 49), ("wav", 5), ("wbmp", 4), ("wdp", 4),
    ("webloc", 96), ("webm", 11), ("webp", 0), ("wem", 81), ("wfm", 68), ("wfp", 20),
    ("wg", 89), ("whl", 70), ("wim", 99), ("wings", 67), ("wld", 74), ("wma", 5), ("wmf", 4),
    ("wmv", 11), ("woff", 34), ("woff2", 34), ("wpd", 36), ("wpl", 21), ("wps", 37),
    ("wpt", 37), ("wri", 37), ("wrl", 66), ("ws", 81), ("wsc", 81), ("wsp", 20), ("wtv", 21),
    ("wv", 10), ("x", 67), ("x3d", 66), ("x3dv", 66), ("x3f", 1), ("x_b", 62), ("x_t", 62),
    ("xapk", 94), ("xar", 71), ("xbm", 4), ("xcal", 90), ("xcard", 90), ("xcf", 27),
    ("xci", 80), ("xd", 26), ("xdelta", 81), ("xln", 65), ("xls", 31), ("xlsb", 31),
    ("xlsm", 31), ("xlsx", 31), ("xltm", 31), ("xltx", 31), ("xm", 10), ("xml", 43), ("xmp", 2),
    ("xpi", 70), ("xpm", 4), ("xps", 36), ("xsf", 68), ("xsl", 50), ("xspf", 21), ("xyz", 65),
    ("xz", 69), ("y4m", 21), ("yaffs2", 99), ("yaml", 43), ("yar", 91), ("yara", 91),
    ("yarnclean", 50), ("ym", 10), ("yml", 43), ("yuv", 21), ("yy", 81), ("yyp", 81), ("z", 69),
    ("z64", 80), ("zabw", 37), ("zae", 66), ("zcode", 63), ("zi", 50), ("zip", 69), ("zoo", 70),
    ("zpr", 61), ("zsh", 50), ("zst", 69), ("ztl", 61),
];

#[cfg(test)]
mod tests {
    use super::*;

    /// The whole premise of the search. A table that came out of the generator
    /// out of order would find about half of what it was asked for, silently.
    #[test]
    fn the_tables_are_sorted_the_way_the_search_expects() {
        assert!(NAMES.windows(2).all(|p| p[0].0 < p[1].0), "NAMES is out of order");
        assert!(SHELVES.windows(2).all(|p| p[0].0 < p[1].0), "SHELVES is out of order");
    }

    /// Every index in the table addresses a family that exists.
    #[test]
    fn every_shelf_points_at_a_family() {
        for (ext, i) in SHELVES {
            assert!((i as usize) < FAMILIES.len(), "{ext} is filed on a shelf that is not there");
        }
    }

    #[test]
    fn a_format_nobody_here_can_open_is_still_named() {
        assert_eq!(name("sldprt"), Some("SolidWorks part"));
        assert_eq!(family("sldprt").map(|f| f.category), Some(Category::ThreeD));
    }

    /// A name off a disk arrives however the file manager spelled it.
    #[test]
    fn the_case_and_the_dot_are_both_forgiven() {
        assert_eq!(name("PNG"), name("png"));
        assert_eq!(name(".Png"), name("png"));
    }

    #[test]
    fn a_stranger_is_a_stranger_rather_than_a_guess() {
        assert_eq!(name("xyzzy"), None);
        assert_eq!(family("xyzzy"), None);
    }
}
